### ISSUE TITLE
Document design for transport::UTransport

### ISSUE THREAD

**Issue by gregmedd** [eclipse-uprotocol/up-cpp#115]
The base `UTransport` object is, in theory, pretty simple. The bulk of the work will be in the individual transport implementations (e.g. `ZenohUTransport`). However, it is possible that `UTransport` might need to do a little more than just pass calls through to its virtual interfaces. This design should consider:

- If `UTransport` needs a thread pool for callbacks (so the transport implementations don't have to do it)
- If `UTransport` should do anything to prevent multiple parallel calls to the same callback (so callbacks don't have to add extra thread safety concerns)
- If there are any threads, how do they get shut down?
- (possibly other things?)

**Comment by cbeck83** [comment]
Recommend Uzi for this one

**Comment by gregmedd** [comment]
The implementation of the base UTransport is not very complex. It does not need a design currently
