### ISSUE TITLE
Implement and test datamodel::validator::Uuid

### ISSUE THREAD

**Issue by gregmedd** [eclipse-uprotocol/up-cpp#118]

**Comment by billpittman** [comment]
I'll take this.

**Comment by BishrutSubedi** [comment]
synced up with Bill, and I'm working on this : )

**Comment by gregmedd** [comment]
Increasing priority to P0 as this is a blocker for the Zenoh transport implementation.

See: [Message on SDV Working Group Slack](https://sdvworkinggroup.slack.com/archives/C074FLEHFCK/p1717182610393199?thread_ts=1717053635.015819&cid=C074FLEHFCK)
