### ISSUE TITLE
Add valgrind run of tests

### ISSUE THREAD

**Issue by gregmedd** [eclipse-uprotocol/up-cpp#127]
The CI workflow should add an extra run of the tests under valgrind to look for memory leaks.

**Comment by gregmedd** [comment]
[This discussion](https://stackoverflow.com/questions/9303711/how-do-i-make-ctest-run-a-program-with-valgrind-without-dart) looks potentially relevant.

**Comment by BishrutSubedi** [comment]
I'm happy to take this task
