### ISSUE TITLE
Write extra NotificationTest for up-cpp

### ISSUE THREAD

**Issue by gregmedd** [eclipse-uprotocol/up-cpp#172]
The “extra” tests provide for more integrated testing than lower-level “coverage” unit tests. They check the interoperation between components. However, they do not count towards code coverage as their assertions are made at a higher level where detailed behaviors may be missed.

This test will exercise the interoperability between NotificationSource and NotificationSink. Are messages produced by one compatible with the other? Does the sink’s listener registration match up with the URIs in a sent notification (i.e. does everything end up in the expected spots)? Does everything validate successfully after being passed through all stages?

**Comment by pranavishere2** [comment]
I can take this
