### ISSUE TITLE
Write extra PublisherSubscriberTest for up-cpp

### ISSUE THREAD

**Issue by gregmedd** [eclipse-uprotocol/up-cpp#173]
The “extra” tests provide for more integrated testing than lower-level “coverage” unit tests. They check the interoperation between components. However, they do not count towards code coverage as their assertions are made at a higher level where detailed behaviors may be missed.

This test will exercise the interoperability between Publisher and Subscriber. Are messages produced by one compatible with the other? Does the Subscribers’s listener registration match up with the URIs in a published message (i.e. does everything end up in the expected spots)? Does everything validate successfully after being passed through all stages?

**Comment by ruchirchauhan** [comment]
I can take this
