### ISSUE TITLE
Write extra RpcClientTest for up-cpp

### ISSUE THREAD

**Issue by gregmedd** [eclipse-uprotocol/up-cpp#174]
The “extra” tests provide for more integrated testing than lower-level “coverage” unit tests. They check the interoperation between components. However, they do not count towards code coverage as their assertions are made at a higher level where detailed behaviors may be missed.

This test will exercise the interoperability between RpcClient and RpcServer. Are messages produced by one compatible with the other? Does the servers’s listener registration match up with the URIs in a request (i.e. does everything end up in the expected spots)? And in the reverse direction for responses? Do responses find their way to the right place? Does everything validate successfully after being passed through all stages?

**Comment by debruce** [comment]
I will work on this.

**Comment by debruce** [comment]
I have a first working full circuit test of this.

**Comment by gregmedd** [comment]
@debruce - Has this been put out for review yet?

**Comment by debruce** [comment]
The PR is here: https://github.com/eclipse-uprotocol/up-cpp/pull/275
I have the following clang-tidy problems:

  Warning: member variable 'rpc_service_uuri_' has public visibility
  Warning: member variable 'ident_' has public visibility
  Warning: all parameters should be named in a function
  Warning: do not use namespace using-directives; use using-declarations instead
  Warning: variable 'client_capture' is not initialized
  Warning: variable 'server_capture' is not initialized
  Warning: variable 'client_handle' is not initialized

Still looking at fixes. Strangely, seems like the CI no longer makes line numbers visible for the locations of the errors.

**Comment by debruce** [comment]
I fixed the various clang-tidy problems with the additions of '// NOLINT' to all of the lines except for rpc_service_uuri and ident, which had a more proper fix.
