### ISSUE TITLE
Confirm the UMessage URI checks align with spec

### ISSUE THREAD

**Issue by gregmedd** [eclipse-uprotocol/up-cpp#188]
> Looking at the [UAttributes spec](https://github.com/eclipse-uprotocol/up-spec/blob/main/basics/uattributes.adoc#2-common-message-attributes), I think we should be checking both the source and sink against specific rules for each message type. However, we may also need additional UUri validators for this. I think I'll file a separate bug for this so it can be investigated more thoroughly.

_Originally posted by @gregmedd in https://github.com/eclipse-uprotocol/up-cpp/pull/184#discussion_r1655347813_

----

The spec indicates that in some message types, there are specific rules for both source _and_ sink URIs. Currently only one of those is checked against specific rules in the UMessage validator code.

**Comment by billpittman** [comment]
I will take a look at this issue.
