### ISSUE TITLE
Enable all warnings in build

### ISSUE THREAD

**Issue by MarkStokes71** [eclipse-uprotocol/up-cpp#189]
Add -Wall to the build (both the main project and the UT's.

**Comment by gregmedd** [comment]
Items this task should address:

1. Add the `-Wall` flag in the main `CMakeLists.txt` file
2. Verify it is also applied to unit tests (this should be propagated from the top-level build file)
3. Address any warnings found.

**Comment by ruchirchauhan** [comment]
I can take this
