### ISSUE TITLE
All code that takes a `shared_ptr<UTransport>` parameter should check for `nullptr`

### ISSUE THREAD

**Issue by gregmedd** [eclipse-uprotocol/up-cpp#193]
This mostly applies to layer 2 communication modules. At the interfaces where the shared pointer is received, it should be checked for `nullptr`. Not all modules do this.

We may want to add a `NullTransport` exception derived from `std::invalid_argument`.

Tests should be added to cover this case.

**Comment by ruchirchauhan** [comment]
I will take this

**Comment by ruchirchauhan** [comment]
Implementation in #261
