### ISSUE TITLE
`using namespace uprotocol::foo;` vs having `uprotocol::foo::Bar` at points of usage in headers

### ISSUE THREAD

**Issue by PLeVasseur** [eclipse-uprotocol/up-cpp#65]
Hey folks :wave: 

Saw some discussion going on internally at GM on whether we should be `using namespace urptotocol::foo;` in headers _or_ in each spot where we need to use `Bar` be writing `uprotocol::foo::Bar`.

Thought I'd open up an issue to let the discussion breathe.

Thus far, the points raised in favor of not `using uprotocol::foo;`:
* These are headers which will be `#include`d often, so:
   * may unintentionally bring in things we don't want into end-user code
   * may cause unintentional name clashes with end-user code

Didn't see points in favor of `using uprotocol::foo;` yet.

Let's use this issue to gather up the pros and cons of each and make the call by Wednesday. Failing that, we could try to steal 10 minutes from the Thursday uProtocol meeting to resolve.

What do y'all think?

**Comment by MarkStokes71** [comment]
I think we should not allow `using` in any headers.  In CPP files, I would recommend against `using` if possible and if using one, then ensure it's in the namespace for the class (not global).

**Comment by cucuzella451** [comment]
Vote to not allow "using namespace" in headers. The most authoritative reference for this C++ Core Guidelines, _SF.7: Don’t write using namespace at global scope in a header file_

https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#sf7-dont-write-using-namespace-at-global-scope-in-a-header-file

**Comment by PLeVasseur** [comment]
> So do we have an agreement ?

Yup, think so. Closing
