### ISSUE TITLE
Add Ability to create UUIDs with timestamp

### ISSUE THREAD

**Issue by stevenhartley** [eclipse-uprotocol/up-cpp#66]
UUID factory `create()` API does not allow us to pass an external timestamp, this means there is no way to test/validate isExpired() and other time related functions. Additionally we cannot inject specific time information. Line in question is here:
https://github.com/eclipse-uprotocol/up-cpp/blob/main/include/up-cpp/uuid/factory/Uuidv8Factory.h#L67C17-L67C23

Example of what is needed can be found in up-java: https://github.com/eclipse-uprotocol/up-java/blob/main/src/main/java/org/eclipse/uprotocol/uuid/factory/UuidFactory.java#L61

Another example implementation in up-rust: https://github.com/eclipse-uprotocol/up-rust/blob/main/src/uuid/uuidbuilder.rs

**Comment by gregmedd** [comment]
This is covered in the 1.5.8 API update for the UUID builder. This will be tracked with the generic _implement UUIDBuilder_ task.
