### ISSUE TITLE
Refactor cloudevent implementation 

### ISSUE THREAD

**Issue by MelamudMichael** [eclipse-uprotocol/up-cpp#71]
1. Refactor cloud event implementation https://github.com/eclipse-uprotocol/up-cpp/tree/main/include/up-cpp/cloudevent
2. Update and write new unit-tests

**Comment by gregmedd** [comment]
@stevenhartley has clarified cloudevent is not needed yet. We can address in the future when cloudevent is needed. Closing issue as won't fix.
