### ISSUE TITLE
Consider supporting std::function when registering callbacks

### ISSUE THREAD

**Issue by gregmedd** [eclipse-uprotocol/up-cpp#78]
_Originally posted by @gregmedd in https://github.com/eclipse-uprotocol/up-cpp/pull/68#discussion_r1532755486_

Taking `std::function` instead of (or in addition to) functor objects would allow for much cleaner implementations in many places and reduce the amount of boilerplate code. Then temporary lambdas and function pointers can be passed as the callback.

For example, in `rpc/RpcClient.h` `UListener` could be redefined as

```
using UListener = std::function<uprotocol::v1::UStatus(uprotocol::utransport::UMessage&)>;
```

Then `invokeMethod()` would be updated to this signature:

```
virtual uprotocol::v1::UStatus invokeMethod(const uprotocol::v1::UUri &topic,
                                            const uprotocol::utransport::UPayload &payload,
                                            const uprotocol::v1::CallOptions &options,
                                            const uprotocol::utransport::UListener &&callback) = 0;
```

(The callback line is now a move `&&` instead of a reference `&`)

If there are strong reasons to keep the functors around as an option, that can be handled by adding a few small adapter interfaces. I put together a [condensed example](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGIAOykrgAyeAyYAHI%2BAEaYxCAArAAcpAAOqAqETgwe3r4BaRlZAqHhUSyx8cm2mPaOAkIETMQEuT5%2BgXaYDtmNzQSlkTFxiSkKTS1t%2BZ0TA2FDFSPJAJS2qF7EyOwc5gDMYcjeWADUJrtuVF4MPQJiZ9gmGgCCj0/MbAqpTFvHXqnEqCIaFop38Vmex0hx3emE%2B30wxwAblxQeCnlCMccAPRY45PBQKHwIy60EFYGgMYoMY4AWmOAGtMJhUmFgMc0AwsAwlOhjvxiMdMKpWKl6K9MVDxsQvA5jnI%2BgQvApUSZ/AARM5ojGqjXPcVQmFwn5eAjEQyfEgEFUQiXY3EeTmMHns2TEPCIww/fnHBRMRnHVBUQXCliizD6iVSmVWuQAWVhvuACNVWttGKYJtQPqaioU2BDYYgy2t6LTtuRIBA8pzSuzTFzmojZYxxEwiuI1PG9aVjZtzZ1Te16t7Lz7mJxE8nU%2BnM9nc/nC5xg6hE%2BOABUAJ6pYkkPlXG4MLEGCroJjssS0aLfenKojHABKqWQbloeEYBErYURqEZ8YICAwItl0hJVWTlNwLyvZB6VOXY1WzdBK0ua56gYM43ArKsFSVCA4wTJgk3MAA2ZZ7hHYC7UXKjqJohcKNXAB5N1gDCMQ5VCcZGDiPcUJICio1lOQOIILiBRTCiMURPAWi8NjMOrbtlVQbczSIYgi1w%2BMCQI5MzBIl1uStM54I0cixzTKSZLYgA/IS8E48J1OLYzjnJDNaAIEc0wHXZU0hAc9WHPVnhxY4HS5Z1ETiTIBAfJ8XzfQRjjvLAWAEKV6wRL8f0wP8AN5Jp6TAzBCAQbjj2iU8AwFZCHD454BKtR9n1fd8SwxUL70wNjst/Nt8uOPBQ3oNhBHrbJjggVINgRSzFR66lvnmkFW3SUixz%2BAEgU8St5Ow5Vety/rAI5cZfn%2BQFUGBSsTTNbl0haSs5Ag0koJg4jRFe69nLBCjNsu66QFu80Ho/KstMTBFgEBNcEHsoRUDYAB3MrWy821W3balPsva9oBhuGFAR5HUcwUjfKbALR1LSFQqeU9UhEgU7wvVAkZ4uriGVCAGEBJFpOWwbFocWSVuZVB1pp86tqunaQD2msDoYb8%2Bv/QD/u22gbtNEHLSe4TRNOPScben6/MxTGNmpQ68sA8ZEJQVsqAgE3vvJ82qabOmGaZ5Ks1Z9mRNDEhmg3Y4KtPW8s1iY40qi3kwkm3mrTm0WheOJa09WiWmw12Wtflrgnv2oWVaOtX0AgPPAeB%2B69arF7cego2iI%2ByDvvajG2yt0ucttyvXeg93KaCl5hwp4KngzO9DoAdVKtdMGDs1iA3YJWEqpgi07yFmoStrTAnqXLY7dkADobeOyuTASKwEjVCBp9QYjY/wpMzYok/qQ%2BSGz67XN8winoEBI%2BQ41TD0Crqamp0rRP2hAIReoZ14njPC5G%2Bd8H5Pxfj/HSH8xxf1ftpJMf9FaAOGpgEBaIfJUOeHAuepVkGb23uJMce9WpJUPubAh9tKwsD9JgAA%2Bl8aSLsL7Kz7lfHmCCl6pEYaeVY59L4VykQwRBsiN7yIgWPKBrxDhMAJMcAAYvuNSxwQDHGmtEV8yBpYAzlrXC0j0qwG0cjvWxmtdpFyworAMKl6wkA0tXexOs65OLwkQ3SREcHvwMmdVAUViBuhOCwqWLZu6n2iZgEhikyGFi0WA8i48aFT0zL3Rk89/zGN4k5NxVTOZ8k1KcVh8V2FWk4U2AhyAxFl37tQLROoOCrC1hwBIvA/AcC0KQVAnA3DWGsD6dYmxdK7B4KQD8EzBmrHpIkDQ%2BhOCSDGZoXg0yOC8AUCAXZ6ytCrDgLAGAiAUCIxZPQMgFAXZPLoCMYAXBdhmD4HQJm5yIDRCOaQaIrFV6cFWeC5gq8GLRG0N0dZqy0AsFGgQBiDBaAblBVgaIXhgCN3OdwXgqVDDAHEBs0g%2BBWw9CisSyZQpugmm2KssIIlhmTNfNEFeG4PBYFBaaIaULBl8AMMABQAA1N8SMGLbnGas/gggRBiHYFIGQghFAqHUFS3QXB9DkpQHMyw%2Bg8DRHOZAVYylULEuOQkpJsJ4CrC6AeFwnIph%2BH1SEeY5RKh6HSJkVCHr/VFFQoMX1Ix9UutQn0SYnh2h6Gjb0WY4bhjxCjbMYNGb%2BipsWOm51iytgSCGZwUZpBxmTJOccVQSQiI0iIpIY4wBkA2J%2BWfMwk1cCEF3HsLgyxeBXM2aQbZCRdnDIOaQFgOzy2gpOWci5ayjk3PuRAJA6wCDTQIOQSgqLnlxAiKwbYNa60NqbS244bazC8EwPgNSeBEL6qVcIT6arpBPq1WoUFerSBIzNKkEVJaRmHKpSchiJpN0BiDMe%2Btjbm2tt2O2yaHhQyfLEmYFZ/bF0bOWKsMqTAsDxCLHsjgE6p2jpnSBzg87LlLq2dO4ZuxgOVqo1h65gGr0UeY6c1jQ6EkxT8JIIAA) for supporting both.

**Comment by debruce** [comment]
Seems like the two invokeMethod's should be combined into one invokeMethod with the listener converted to an std::optional<Listener>, too.

**Comment by gregmedd** [comment]
Callables are covered in the 1.5.8 API redesign.
