### ISSUE TITLE
Consider formal adoption of C++ exceptions for up-cpp implementation for error handling

### ISSUE THREAD

**Issue by debruce** [eclipse-uprotocol/up-cpp#79]
It is the case that uuri handling code can throw exceptions from string manipulation functions like std::stoi(). This presents a problem as it is inconsistent with the error-by-return-value approach of the rest of the API. I recommend that the entire API adopt a std::stdexcept based error handling approach to make it easier for end users to write code. End users and test cases will need to make liberal use of thread and futures and such, and these things do error handling by stdexcept.

**Comment by gregmedd** [comment]
I agree that we need to standardize how we propagate errors in our C++ libraries. In my experience, exceptions are often the best way to do this with one caveat - catching exceptions is _expensive_ in C++ [citation needed]. Throwing exceptions for a _fall over and catch fire_ situation is pretty good. However, any situation where a result is expected to be used for flow control (e.g. when good, do x, when bad, do y) is better off using return values.

One of the biggest benefits of using exceptions, in my experience, is that it makes issues _extremely_ visible during development and test. A silent error from an unchecked result can be missed for a long time, even into production, resulting in small, unexpected behaviors. An exception cannot be missed (unless caught and discarded, but as mentioned above any catching of exceptions should be closely scrutinized).

An alternative that I think we should consider here is returning `[[nodiscard]] std::variant<ErrorT, ReturnT>` from operations that can fail. This _forces_ the caller to check what type was returned, and will throw an exception if the caller assumes `ReturnT` without at least confirming that the result wasn't an error. It gives us _some_ of the benefits of exceptions, while also allowing results to be used for efficient flow control.

**Comment by gregmedd** [comment]
With an active API review and plans to refresh, we should resolve this. Are there any requirements that are preventing us from using exceptions more extensively? Any alternatives we should be considering? With the state of the API right now, there is no consistent way to propagate errors.

**Comment by gregmedd** [comment]
A solution has been picked, and a documentation task is being added to the 1.5.8 project. This issue has been resolved.
