### ISSUE TITLE
Consider exposure of zenoh rust logging mechanism to C++ API for common logging. 

### ISSUE THREAD

**Issue by debruce** [eclipse-uprotocol/up-cpp#80]
Both the rust layer and C++ layer do logging. The C++ layer is using spdlog. It makes sense that there should be only one logging mechanism. The two options for combining them are:
1) Provide a C function callback to the rust layer to use as its logging function.
2) Expose the rust logging function as a C function to C++

My preference would be for option 2.

**Comment by stevenhartley** [comment]
@debruce This has nothing to do with up-cpp project, please file the issue on up-client-zenoh-cpp
