### ISSUE TITLE
Expose the ability to set, get, and enumerate the rust layer config parameters to C++.

### ISSUE THREAD

**Issue by debruce** [eclipse-uprotocol/up-cpp#81]
The zc_config_insert_json function exposed from rust to C++ sets useful key/value pairs. Some of these may be necessary for full use case coverage, and some may facilitate testing (like disabling memory loopback to force multicast paths to be exercised).

**Comment by gregmedd** [comment]
I have two concerns. First one is minor: this looks like it is an issue that is specific to [up-client-zenoh-cpp](/eclipse-uprotocol/up-client-zenoh-cpp) and should probably be filed there.

Second is about the need for this interface. Is this only to allow for testing more code paths through zenoh-c? Or do we need this outside of testing? It sounds like this would only allow for testing the different paths through zenoh-c, which could fall outside of the scope of unit tests in up-client-zenoh-cpp. If there are unique behaviors to zenoh-c interfaces that are dependent on the transmission mechanism (e.g. extra return codes), those could be tested using mocks.

We should be really careful about expanding tests that will be used to generate coverage reports _beyond_ the scope of unit testing. I am all for adding more extensive integration and functional tests, but recommend that we take care to keep them clearly separated from our unit tests. It would be very easy for a broad test to "cover" lines of code without providing assertions on the behavior of those lines, falsely inflating our coverage reporting (when we get around to adding it).

**Comment by debruce** [comment]
There are two issues I've conflated together with this. One is the config parameters that need exposure, and the other is config parameters that don't need exposure for client use and high level unit tests. The second issue should be dealt with in up-client-zenoh-cpp. There has been some discussion on the first issue in group chat, but I don't recall who. It was probably Michael and Steven. Maybe, they should raise the connect and listen key issue. Or, I can revisit it at a future time.

For now, I'll close this.
